src/web/controllers/UserController.php
<?php

declare(strict_types=1);

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

namespace antichris\rssReader\web\controllers;

use antichris\rssReader\user\authentication\AuthenticationService;
use antichris\rssReader\user\authentication\LoginFormProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller as BaseController;
use yii\web\User;

/**
 * Provides user authentication (login/logout) interface.
 */
class UserController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function __construct(
        $id,
        $module,
        private AuthenticationService $loginService,
        private LoginFormProvider $formProvider,
        private User $userComponent,
        $config = [],
    ) {
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    ['allow' => true, 'actions' => ['logout'], 'roles' => ['@']], // Allow authenticated users.
                    ['allow' => true, 'actions' => ['login'], 'roles' => ['?']], // Allow unauthenticated ones.
                    ['allow' => false, 'actions' => ['login'], 'roles' => ['@'], // Deny authenticated users.
                        'class' => RedirectHomeAccessRule::class, ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'login' => ['GET', 'POST'],
                    'logout' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Renders and validates the login form.
     *
     * @return tActionResult
     */
    public function actionLogin()
    {
        $form = $this->formProvider->provide([$this->loginService]);

        if ($form->load($this->request->post()) && $this->loginService->login($form)) {
            return $this->goBack();
        }

        $form->password = '';

        return $this->render('login', [
            'model' => $form,
        ]);
    }

    /**
     * Logs out the user.
     *
     * @return tActionResult
     */
    public function actionLogout()
    {
        $this->userComponent->logout();

        return $this->goHome();
    }
}

src/web/views/layouts/main.php
<?php declare(strict_types=1);

use antichris\rssReader\web\assets\AppAsset;
use antichris\rssReader\web\View;
use antichris\rssReader\web\widgets\Alert;
use yii\bootstrap5\Nav;
use yii\bootstrap5\NavBar;
use yii\helpers\Html;

/** @var View $this */
/** @var string $content */
AppAsset::register($this);
?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= $this->language; ?>">
<head>
    <meta charset="<?= $this->charset; ?>">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags(); ?>
    <title><?= Html::encode($this->title); ?></title>
    <?php $this->head(); ?>
</head>
<body>
<?php $this->beginBody(); ?>
<?php
NavBar::begin([
    'brandLabel' => $this->appName,
    'brandUrl' => $this->homeUrl,
    'options' => [
        'class' => 'navbar-expand-md navbar-dark bg-dark fixed-top',
    ],
    'innerContainerOptions' => ['class' => 'container-md'],
]);
echo Nav::widget([
    'options' => ['class' => 'navbar-nav ms-auto'],
    'items' => [
        $this->userComponent?->isGuest ? (
            ['label' => 'Log In', 'url' => ['/user/login']]
        ) : (
            '<li class=nav-item>'
            . Html::beginForm(['/user/logout'], 'post')
            . Html::submitButton('Log Out', ['class' => 'btn nav-link'])
            . Html::endForm()
            . '</li>'
        ),
    ],
]);
NavBar::end();
?>
<main class=container-md>
    <?= Alert::widget(); ?>
    <?= $content; ?>
</main>
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>